### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by IliaPos** [Solana0x/nodepay#13]
Sorry for the possibly bad question.

I created several nodepay accounts and found out that they need to be activated, which gives me an "access denied" error. I tried changing the IP address, but it still doesn't work. Are there ways to get around this?

**Comment by IliaPos** [comment]
> Ok then you can do that one by one install extension and just for 2-3 mins run Via the correct way of Downloading extension after that remove extension and get your NP token ! also token expires every 15 days so you need new tokens every 15 Days!

thanks, I'll try when I get home from work

**Comment by Solana0x** [comment]
ok
