### ISSUE TITLE
Proxy error message

### ISSUE THREAD

**Issue by ruanling** [Solana0x/nodepay#2]
![image](https://github.com/Solana0x/nodepay/assets/33116879/9652f4ed-f864-4f5b-90e3-9d1f63fa68d5)
![image](https://github.com/Solana0x/nodepay/assets/33116879/fc9b3c01-d334-4d51-a9b0-b72894c23cda)

My proxy active, I put it in the correct format HTTP://username:pass@ip:port, but it still gives me the error

**Comment by Solana0x** [comment]
i have tried almost all the proxy sellers available in the market but mostly dont open port for nodepay website only as of now i know Webshare website which i shared in the Github readme open the port so please buy their plan if you get proxies from other websites it wont work

**Comment by rambetiko** [comment]
How can we use it without proxy if the pc is on 7/24?

**Comment by khanh8910** [comment]
> i have tried almost all the proxy sellers available in the market but mostly dont open port for nodepay website only as of now i know Webshare website which i shared in the Github readme open the port so please buy their plan if you get proxies from other websites it wont work

Webshare is currently blocked, right?

**Comment by Solana0x** [comment]
Webshare is working ! possibly last few days nodepay site was under maintenance

![image](https://github.com/Solana0x/nodepay/assets/142747768/a17cd99c-fd9c-42d9-99d3-3c42cfbc47b2)

**Comment by khanh8910** [comment]
I received this error message when connecting to some webshare IPs:
Connection error : server rejected WebSocket connection: HTTP 403

**Comment by Solana0x** [comment]
Then surely error from Nodepay site possibly blocked the Proxy
