### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by doubleTroub1e** [Solana0x/nodepay#3]
does it work fine for you?

**Comment by doubleTroub1e** [comment]
any update @Solana0x ?

**Comment by Solana0x** [comment]
its working FIne please use the webshare website to buy proxy instead of Proxies.fo !

**Comment by akton0208** [comment]
which package in webshare? datacentre?

**Comment by Solana0x** [comment]
You can buy the below one i have buyed also one plan can be used for multiple Nodepay gmail accounts i am running on 20 accounts and earning ~ 25-30M per day from all accounts combined my code uses least bandwidth as compared to any other code on the Github !! IF you wana earn more you can buy 2500 Proxy also but buy datacenter ones !!

https://www.webshare.io/?referral_code=gppl5h10bwn5

![image](https://github.com/Solana0x/nodepay/assets/142747768/c0a6602f-58aa-40d1-b58c-a888cdee25f1)
![image](https://github.com/Solana0x/nodepay/assets/142747768/55cf6de5-d14b-4aba-9738-2454d173f5c9)
