### ISSUE TITLE
Big  problem 

### ISSUE THREAD

**Issue by kaicao90** [Solana0x/nodepay#6]
I have a problem that when I run node.py once, it automatically closes and the proxy information file deletes all the proxy data that I added...
Do you have this problem?
If not, how can I fix it?

**Comment by kaicao90** [comment]
I checked and the proxy file is automatically deleting data.
I don't know if the proxy is losing connection and being deleted because it says error 22

**Comment by Solana0x** [comment]
please use the webshare proxy ! the other website doesnt works sometimes

**Comment by Solana0x** [comment]
Buy the proxy from the Given link in the Github in future i will add more as i will test and come to know about

**Comment by duyettran** [comment]
I bought the webshare proxy but got this error:
Connection error: server rejected WebSocket connection: HTTP 403

**Comment by Solana0x** [comment]
i am also facing this error last 2 days seems like Nodepay guys in recent update blocked for webshare may be* i need time to find currently i am working on grass node 1.25x booster script

**Comment by kaicao90** [comment]
Alright, I'll wait for you to upgrade. Thank you
