### ISSUE TITLE
Server rejected websocket connection http 503

### ISSUE THREAD

**Issue by ngphat** [Solana0x/nodepay#8]
I have problem today with exception : server rejected websocket connection http 503
Can you take a look ?

**Comment by RanSack620** [comment]
I had same issue.

**Comment by asheartz** [comment]
Same here. Anyone with a fix?

**Comment by DONpromise1738-dot** [comment]
Same issue 😭 please fix

**Comment by Solana0x** [comment]
sorry @DONpromise1738-dot i will update everything by today ! sorry was little busy since last week

**Comment by DONpromise1738-dot** [comment]
Thanks boss the new update is working highly appreciated boss

**Comment by Solana0x** [comment]
Thanks :)
